// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kyvqhdrcscfuxkprceem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5dnFoZHJjc2NmdXhrcHJjZWVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NDMyNDAsImV4cCI6MjA2OTMxOTI0MH0.cv2KAN2EcJFwsjsOm7RpsMOjx45C1W1N_Usg-xbD6Eo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});